### ISSUE TITLE
Initial feedback

### ISSUE THREAD

**Issue by CFGrote** [ejcjason/MDDomainExtension#1]
I copy my mail sent earlier here for reference

good work! we have to be sure that all data in the xmdyn output is
properly represented. in general, i would like to include all metadata
that would be needed to rerun/restart the simulation. in particular this
means information about the force field, the code being used for the
simulation.

can you get openpmd-api to read/write a file conforming to such a standard?

we would then need a converter from xmdyn output to openpmd. i think there is a prototype somewhere in simex.

it's a very good first draft, more than i was hoping for at this stage!

best regards, enjoy your weekend!

**Comment by JunCEEE** [comment]
The code being used is recorded in the root attribute `software ` . As for force field, is it like the electric field defined in PiconGPU? In my experience in LAMMPS, I just calculated the force from interatomic potentials before.

I will check again:
- [x] openPMD-api to add groups in different steps.
- [ ] the xmdyn converter.

**Comment by JunCEEE** [comment]
I added the attributes of forceField and its parameters, but I just found that it is still not enough to reproduce a dataset from the metadata. For example, a dataset was created by an NPT process in which temperature was reduced by 100 K every 5000 steps. This kind of operation seems too cumbersome to be recorded in the metadata, but you cannot rerun the simulation without knowing that.

**Comment by CFGrote** [comment]
don't have to record the entire process, just the information: NPT,
starting T, final T, T step and what else is needed to know.

**Comment by JunCEEE** [comment]
> can you get openpmd-api to read/write a file conforming to such a standard?

It is now right here:
https://github.com/ejcjason/MDDomainExtension/blob/master/openPMDMD.py

See also https://github.com/ejcjason/MDDomainExtension
